### ISSUE TITLE
Parameter order seem strange between global and extensions

### ISSUE THREAD

**Issue by neomatamune** [clk-project/clk#24]
```bash
clk extension --global create test_extension
clk extension enable test_extension
clk parameter --extension test_extension set log Extension
clk parameter --global set log Global
clk log User
```
The last command should display `Global Extension User` but will instead display `Extension Global User`

We would suppose that the priority of parameters should be global, extension, user parameters instead we get extension, global, user parameters

**Comment by Konubinix** [comment]
This is on purpose.

The rationale is that configuration put in extensions come by default and you override them in your computer in global.

Can you tell me more about the use case?
1. either I may help you achieve what you want with the current state of clk,
2. or we can write your story and implement it somehow.

I any case, the order of the profiles is not documented in the [use cases](https://clk-project.org/doc/use_cases/). I'm adding this to my maybe list :-).

**Comment by Konubinix** [comment]
In fact, my current focus is on documenting extensions, from the creation to the sharing. So thanks to you I know that in this documentation, I should tell about the rationale why we have this ordering.

**Comment by neomatamune** [comment]
The idea we had was to use extension to change sets of commands parameters by toggling extensions.
We could have a default set of parameters using the global, then by activating an extension we could change the set of parameters used.
We would want a set of uses that goes like following priorities (lower to higher) :
- Use the global configuration
- Use an extension if it is activated
- Use given parameter from the command line
That way depending on context we could easily switch sets of settings, for example enabling a full debug mode using a "debug" extension

**Comment by Konubinix** [comment]
This looks legit to me.

When I will write about extensions, I will try to tell about both use
cases: the extension that comes with default values that you overwrite
in global and the extension that is enabled with the aim of overwriting
global. And afterwards I will be able to implement those.

To help me write something that actually makes sense, could you be a
little bit more specific about the extension you are trying to
setup. The more concrete the story, the more likely I will be able to
develop something that will answer real life problems.

For instance, I have in mind to talk about video editing and
playing. The user starts by creating wrappers around ffmpeg, catt,
handbrake etc, then bring them together in an extension, share it in
github. Then someone else gets the extension and use global parameters
and aliases to make the extension adjust to whatever expectation per
has. This will show how extensions can be created, used and customized
while providing a concrete example. This is a real life use case of
mine.

So, what is your concrete example that we can narrate so as tl
illustrate the other kind of extension usage?

**Comment by Konubinix** [comment]
Still no work about documenting extensions has started.

I think that a outside point of view could be a good bootstrap for this
documentation.

Could you try to tell me why someone would use extension, and how per would create/use/install
them? That would be very useful.

**Comment by Konubinix** [comment]
@neomatamune

Hi. Just for your information, there is still nothing planned in the near future
to deal with this.

How did you work around this issue?

**Comment by Konubinix** [comment]
Due to the lack of interest in this issue. I closed it. Feel free to reopen it
in case you want to continue the conversation.
